"""
Parameters to test basic functionality.
"""

#Task I
MEAN_ERROR_THRESHOLD = 5
PERCENTILE_95_THRESHOLD = 10
MEDIAN_ERROR_THRESHOLD = 4

#Task II
CARDINALITY_ERROR_THRESHOLD = 1

#Task III
HEAVY_HITTERS_THRESHOLD = 90